# Name of your site (displayed in the header)
name: Nina Gernow

# Site info
url: https://www.ninagernow.com

title: Nina Gernow - love and light, peace, mind, awareness, happiness, you have it all!

# Used for Sitemap.xml and your RSS feed
imagesurl: https://www.ninagernow.com/images

# Short bio or description (displayed in the header)
description: Love and light, peace, mind, awareness, happiness, you have it all! By Nina Gernow

github: Nina Gernow
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false

#theme: jekyll-theme-cayman
#theme: jekyll-theme-leap-day
theme: minima

gfm_quirks: paragraph_end

plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: nina.gernow@gmail.com
  facebook: 
  flickr: 
  github: 
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: 

# Your disqus shortname, entering this will enable commenting on posts
disqus: 

# Enter your Google Analytics web tracking code (e.g. UA-xxxxx-x) to activate tracking
google_analytics: 

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: 
  list-id: 



